/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/SdbTHJXCyMb
 */
import { TabsTrigger, TabsList, TabsContent, Tabs } from "@/components/ui/tabs"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import {Button} from "@/components/ui/button";
import { FaDiscord } from "react-icons/fa";
import { useState } from "react"
import { useForm } from "react-hook-form";
import { useUserSessionStore } from "@/hooks/state/useSession"
import Link from "@/components/ui/link";
export function LoginForm({
  onClose
}:{
  onClose?:()=>void
}) {
  const user = useUserSessionStore((state) => state.user)
  const isLoading = useUserSessionStore((state) => state.isLoading)
  const isLoggedIn = useUserSessionStore((state) => state.isLoggedIn)
  const login = useUserSessionStore((state) => state.login)
  const { register, handleSubmit, watch, formState } = useForm({
    defaultValues: {
      email: "",
      password: "",
    }
  });
  //@ts-ignore
  const onSubmit = async (event) => {
    event.preventDefault();
    await login({
      username: watch("email"),
      password: watch("password"),
    })
    onClose?.()
  }
  return (
        <Tabs className="w-full" defaultValue="signin">
            <TabsList className="grid w-full grid-cols-2 bg-slate-100 rounded-lg">
            <TabsTrigger value="signin">
              Sign In
            </TabsTrigger>
            <TabsTrigger value="signup">
              Sign Up
            </TabsTrigger>
          </TabsList>

          <TabsContent className="p-4" value="signin">
            <form className="space-y-4 w-full"  onSubmit={onSubmit}>
              <div className="space-y-2">
                <Label htmlFor="signin-email">Email</Label>
                <Input id="signin-email" {...register("email", { required: true })} />
              </div>
              <div className="space-y-2">
                <div className="flex justify-between">
                <Label htmlFor="signin-password">Password</Label>
                    <Link href="#">
                      Forgot Password?
                    </Link>
                </div>
                <Input id="signin-password" type="password" {...register("password", { required: true })} />
              </div>
                <div className="flex">
                    {
                        isLoading ? (
                            <Button type="submit" variant={"ghost"} className="ml-auto mr-2" disabled>
                                Loading...
                            </Button>
                        ) : (
                            isLoggedIn ? (
                              <Button type="submit" variant={"ghost"} className="ml-auto mr-2" disabled>
                                  Logged in as {user?.username}
                              </Button>
                            ) : (
                              <Button type="submit" variant={"ghost"} className="ml-auto mr-2">
                                  Sign In
                              </Button>
                            )
                        )
                    }
                </div>
              <div className="flex justify-center mt-4 items-center">
                <FaDiscord className="w-6 h-6" />
              </div>
              <div className="flex justify-center mt-4">

              </div>
            </form>
          </TabsContent>
          <TabsContent className="p-4" value="signup">
            <form className="space-y-4 w-full">
              <div className="space-y-2">
                <Label htmlFor="signup-email">Email</Label>
                <Input id="signup-email" required type="email" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="signup-username">Username</Label>
                <Input id="signup-username" required type="text" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="signup-password">Password</Label>
                <Input id="signup-password" required type="password" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="signup-repeat-password">Repeat Password</Label>
                <Input id="signup-repeat-password" required type="password" />
              </div>
              <div className="flex">
                <Button type="submit" variant={"ghost"} className="ml-auto mr-2">
                    Sign Up
                </Button>
              </div>

              <div className="flex justify-center mt-4 text-sm text-gray-500">
                By clicking Register, you agree to beatsaver.com&apos;s
                <Link className="text-blue-500" href="#">
                  Terms of Service
                </Link>
                .{"\n                          "}
              </div>
            </form>
          </TabsContent>
        </Tabs>
  )
}
